// Module included in the following assemblies:
// * networking/installing-albo-sts-cluster.adoc

:_mod-docs-content-type: PROCEDURE
[id="creating-aws-iam-role-ccoctl_{context}"]
= Creating an IAM role for the AWS Load Balancer Operator

An additional AWS IAM role is required to successfully install the AWS Load Balancer Operator on a cluster that uses STS. You can use the Cloud Credential Operator utility (`ccoctl`) to create this role.

.Procedure

. Download the `CredentialsRequest` custom resource (CR) and store it in a directory by running the following command:
+
[source,terminal]
----
$ oc adm release extract --credentials-requests \
   --cloud=aws \
   --to=<path_to_directory_with_list_of_cr_requests> \
   quay.io/openshift-release-dev/ocp-release:4.13.x-x86_64 <1>
----
<1> Replace `4.13.x` with the specific version of your cluster.

. Use the `ccoctl` utility to create an AWS IAM role by running the following command:
+
[source,terminal]
----
$ ccoctl aws create-iam-roles \
   --name <name> \ <1>
   --region=<aws_region> \
   --credentials-requests-dir=<path_to_directory_with_list_of_cr_requests> \
   --identity-provider-arn=arn:aws:iam::<aws_account_id>:oidc-provider/<oidc_issuer_url>
----
<1> `<name>` is the name used to tag the cloud resources created by `ccoctl`. You can use the infrastructure ID of your cluster.

. Note the **Amazon Resource Name (ARN)** of the AWS IAM role created for the AWS Load Balancer Operator from the output (e.g., `arn:aws:iam::777777777777:role/<name>-aws-load-balancer-operator-aws-load-balancer-operator`).