// Module included in the following assemblies:
//
// * networking/understanding-networking.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-understanding-networking-pod-to-service-example_{context}"]
= Example: Controlling pod-to-service communication

.Procedure

Imagine you have a microservices-based application with two components: a front-end and a back-end. The front-end needs to communicate with the back-end to fetch data.

. Create a back-end service:
+
   [source, yaml]
   apiVersion: v1
   kind: Service
   metadata:
     name: back-end
   spec:
     selector:
       app: back-end
     ports:
       - protocol: TCP
         port: 80
         targetPort: 8080

. Configure back-end pods:
+
   [source, yaml]
   apiVersion: v1
   kind: Pod
   metadata:
     name: back-end-pod
     labels:
       app: back-end
   spec:
     containers:
       - name: back-end-container
         image: my-back-end-image
         ports:
           - containerPort: 8080

. Establish front-end communication: 

The front-end pods can now use the DNS name `back-end.default.svc.cluster.local` to communicate with the back-end service.

The service ensures that the traffic is routed to one of the back-end pods.

Service-to-pod communication abstracts the complexity of managing pod IPs and ensures reliable and efficient communication within the Kubernetes cluster. 
