:_mod-docs-content-type: PROCEDURE
[id="querying-gateway-status-cli_{context}"]
= Querying Gateway infrastructure status using the CLI

[role="_abstract"]
When you need to quickly check the health of your Gateway infrastructure, you can query specific status fields using the {product-title} CLI. Using targeted queries allows you to validate your deployment, check route attachments, and retrieve assigned IP addresses without having to manually parse through lengthy YAML manifests.

.Prerequisites

* You have access to the cluster as a user with the `cluster-admin` role.
* You have installed the {oc-first}.

.Procedure

* To list all `GatewayClass` resources in your cluster, run the following command:
+
[source,terminal]
----
$ oc get gatewayclass
----

* To check if a specific `GatewayClass` has been accepted by the controller, run the following command:
+
[source,terminal]
----
$ oc get gatewayclass <gatewayclass_name> -o jsonpath='{.status.conditions[?(@.type=="Accepted")].status}'
----

* To list all `Gateway` resources across all namespaces, run the following command:
+
[source,terminal]
----
$ oc get gateway -A
----

* To check if a specific `Gateway` is successfully programmed in the data plane, run the following command:
+
[source,terminal]
----
$ oc get gateway <gateway_name> -n <namespace> -o jsonpath='{.status.conditions[?(@.type=="Programmed")].status}'
----

* To retrieve the IP address assigned to a specific `Gateway`, run the following command:
+
[source,terminal]
----
$ oc get gateway <gateway_name> -n <namespace> -o jsonpath='{.status.addresses[0].value}'
----

* To check the total number of routes attached to a specific `Gateway`, run the following command:
+
[source,terminal]
----
$ oc get gateway <gateway_name> -n <namespace> -o jsonpath='{.status.listeners[*].attachedRoutes}'
----

* To watch a specific `Gateway` for real-time status changes, run the following command:
+
[source,terminal]
----
$ oc get gateway <gateway_name> -n <namespace> -w
----